Login, registro e verificação do token
2019-2-arquitetura-desenho/monitoria-api pull request #12
Opened 2019-09-25 16:38 UTC by gustavolima00

## Descrição

Pull requeste referente às issues [Cadastro](#3) e [Login](#6), o login e cadastro é feito ultilizando email e senha e é retornado o token jwt para ser ultilizado na aplicação

## URLs
- Registro
/auth/registration

- Login
/auth/login

- Verificação do token
/auth/token_verify

2019-09-25 18:07 UTC, WelisonR requested changes
Não consegui criar dois usuários no banco de dados. Aparentemente, o erro está relacionado ao campo "username" que tem uma constraint de unicidade, não pode ser duplicado.
Dê os assigns da issue, adicione a sprint referente, as labels e etc.

![image](https://user-images.githubusercontent.com/31112450/65627495-dfde5a80-dfa5-11e9-8f9f-1bf84600bbb4.png)

2019-09-25 20:32 UTC, gustavolima00 commented
> Não consegui criar dois usuários no banco de dados. Aparentemente, o erro está relacionado ao campo "username" que tem uma constraint de unicidade, não pode ser duplicado.
> Dê os assigns da issue, adicione a sprint referente, as labels e etc.
> 
> ![image](https://user-images.githubusercontent.com/31112450/65627495-dfde5a80-dfa5-11e9-8f9f-1bf84600bbb4.png)

Resolvido!! :+1:

2019-09-26 16:49 UTC, WelisonR commented
A criação de contas, o login e a verificação do token estão **funcionando corretamente**. Fica como próxima atividade de outra issue, devido a necessidade de integrar o frontend:
- [x] Token JWT deve se renovar a cada ação do usuário no app.

Ótimo trabalho!!

2019-09-26 16:50 UTC, WelisonR approved these changes

2019-09-26 16:50 UTC, merged