Addition of delete profile URL
2019-2-arquitetura-desenho/monitoria-api pull request #26
Opened 2019-10-15 22:27 UTC by gustavolima00

## Descrição

Pull request referente a issue [ Deletar conta ](https://github.com/2019-2-arquitetura-desenho/monitoria-api/issues/8) que consiste em deletar a conta de um usuário ultilizando seu token jwt

## Como Rodar
  Basta acessar a URL e entrar com o json e o servidor retorna 200 caso o usuário foi deletado 
#### URL
<http://localhost:8000/delete_profile/>

#### Request
- token

2019-10-16 01:33 UTC, andrelucax requested changes

2019-10-16 01:33 UTC, andrelucax commented on profiles/urls.py
> +    path('activate_profile/', views.activate_profile),
Creio que podemos deixar a ativacao novamente da conta pelo mesmo link de criar conta, possuir um link para ativar conta e um link parar criar conta pode acabar confundindo usuarios que desativaram a conta

2019-10-16 01:33 UTC, andrelucax commented on profiles/views.py
> +unactive_profile = Response(data={'non_field_errors':['Perfil não existe']} ,status=HTTP_404_NOT_FOUND)
non_field seria sem campo, nao? nao condiz com o erro

2019-10-16 01:33 UTC, andrelucax commented on profiles/views.py
> +unactive_user = Response(data={'non_field_errors':['Usuário não existe']} ,status=HTTP_404_NOT_FOUND)
non_field seria sem campo, nao? nao condiz com o erro

2019-10-16 01:33 UTC, andrelucax commented on profiles/views.py
> +        return unactive_user
usuario nao existe ou nao ta ativo? tem diferenca mas a linha de cima diz uma coisa e o retorno outro.

2019-10-17 18:40 UTC, gustavolima00 commented on profiles/views.py
> +unactive_profile = Response(data={'non_field_errors':['Perfil não existe']} ,status=HTTP_404_NOT_FOUND)
Estou seguindo um formato de retorno de erro padrão do django, que fica facil para se tratar no FrontEnd

2019-10-17 18:42 UTC, gustavolima00 commented on profiles/urls.py
> +    path('activate_profile/', views.activate_profile),
Por necessitar de uma confirmação para reativação de conta acredito que essa ativação pelo login pode ser feita pelo FrontEnd tranquilamente.

2019-10-23 23:14 UTC, gustavolima00 commented on profiles/views.py
> +unactive_user = Response(data={'non_field_errors':['Usuário não existe']} ,status=HTTP_404_NOT_FOUND)
É um padrão retornar erros não associados a campos assim, como por exemplo, falha ao fazer login por password ou senha incorretos

2019-10-23 23:17 UTC, gustavolima00 commented on profiles/views.py
> +        return unactive_user
Resolvido

2019-10-24 01:43 UTC, closed without merging